[package]
name = "rust_cosmos_sample"
version = "0.1.0"
edition = "2018"

[dependencies]
azure_data_cosmos = "0.12.0"
azure_core = "0.12.0"
tokio = { version = "1.28.2", features = ["macros"] }
actix-cors = "0.6.4"
actix-rt = "2.2.0"
actix-web = "4.3.1"
arrayvec = "0.7.1"
once_cell = "1.8.0"
reqwest = "0.11.4"
rand = "0.8.4"
serde_json = "1.0.67"
serde = { version = "1.0.123", features = ["derive"] }
env_logger = "0.10.0"
azure_sdk_core = "0.43.7"
futures = "0.3.28"
log = "0.4.19"
anyhow = "1.0.71"
tracing = "0.1.37"

